theme: jekyll-theme-minimal
title: ADA Template Website Changed
description: A template website for ADA Changed by Leonor
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
